title: VV5D
email: contact@vv5d.nl
# description: >-
#  Dit is de site van de VV5D, de par
baseurl: ""
url: "http://vv5d.nl" 
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
